#' Monthly Fire Weather and Burned Area Data (Simulated)
#'
#' A simulated dataset created for the Bushfire Explorer app.
#' It mimics the relationship between Fire Weather Index (FWI) and
#' burned area in bushfire events across different months.
#'
#' The data are generated in `data-raw/make_data.R` for demonstration
#' purposes — not from real records — and are used in the Shiny app
#' to explore how higher FWI values are associated with larger burned areas.
#'
#' @format A data frame with 100 rows and 3 variables:
#' \describe{
#'   \item{month}{Month of observation (Jan–Dec).}
#'   \item{FWI}{Fire Weather Index (higher = more dangerous fire conditions).}
#'   \item{burned_area}{Area burned (hectares, plotted as \code{log10(burned_area)}).}
#' }
#' @source Simulated data generated by Quanyu Qian (2025) in `data-raw/make_data.R`.
#'
#' @examples
#' # View first few rows
#' head(se_fire_monthly)
"se_fire_monthly"
